# version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  api:
    build: ./backend
    env_file:
      - ./.env
    container_name: mia-api
    restart: always
    ports:
      - ${PORT}:${PORT}

  frontend:
    build: ./frontend
    container_name: mia-frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - api

